apiVersion: 1

datasources:
  - name: MySQL Weather DB
    type: mysql
    access: proxy
    url: mysql:3306
    database: weather_db
    user: weather_user
    secureJsonData:
      password: weather_pass
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    editable: true
    isDefault: true
